#!/bin/bash

# Get the secret as the first argument
SECRET="${@}"
: ${SECRET:=`btsync --generate-secret`}

echo "Starting btsync with secret: $SECRET"

# Replce the secret in the config file
sed -i "s/__SECRET__/$SECRET/" /btsync/btsync.conf

btsync --config /btsync/btsync.conf --nodaemon